# Generated by Django 4.2.30 on 2026-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='result_image',
            field=models.ImageField(blank=True, default='', upload_to='results/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='result_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
